<script setup>
import { ref } from 'vue'
defineProps({ route: { type: String, required: true }, query: { type: Object, default: () => ({}) }, cartCount: { type: Number, default: 0 }, wishlistCount: { type: Number, default: 0 } })
const emit = defineEmits(['navigate', 'search'])
const menuOpen = ref(false)
const searchOpen = ref(false)
const searchTerm = ref('')
function go(path) { menuOpen.value = false; emit('navigate', path) }
function submitSearch() { if (searchTerm.value.trim()) { emit('search', searchTerm.value.trim()); searchOpen.value = false } }
</script>

<template>
  <header class="site-header"><div class="header-shell"><a class="brand" href="/" @click.prevent="go('/')"><span class="brand-mark">N</span><span>NEXUS<span class="accent">//</span></span></a><nav class="primary-nav" :class="{ open: menuOpen }" aria-label="Primary navigation"><a href="/" :class="{ active: route === '/' }" @click.prevent="go('/')">Home</a><a href="/products" :class="{ active: route.startsWith('/products') && !query.category && query.deals !== 'true' }" @click.prevent="go('/products')">Products</a><a href="/products?category=Accessories" :class="{ active: route === '/products' && Boolean(query.category) }" @click.prevent="go('/products?category=Accessories')">Categories</a><a href="/products?deals=true" :class="{ active: route === '/products' && query.deals === 'true' }" @click.prevent="go('/products?deals=true')">Deals</a><a href="/about" :class="{ active: route === '/about' }" @click.prevent="go('/about')">About</a><a href="/account" class="mobile-account-link" :class="{ active: route === '/account' }" @click.prevent="go('/account')">Account</a></nav><div class="header-actions"><button type="button" class="header-icon search-trigger" aria-label="Search products" @click="searchOpen = !searchOpen">⌕</button><a href="/wishlist" class="header-icon with-count" aria-label="Wishlist" @click.prevent="go('/wishlist')">♡<b v-if="wishlistCount">{{ wishlistCount }}</b></a><a href="/cart" class="header-icon with-count" aria-label="Shopping cart" @click.prevent="go('/cart')"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M6 8.5h12l-1 11H7l-1-11Z" /><path d="M9 8.5V7a3 3 0 0 1 6 0v1.5" /></svg><b v-if="cartCount">{{ cartCount }}</b></a><a href="/account" class="header-icon account-link" aria-label="Account" @click.prevent="go('/account')"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="8" r="3.25" /><path d="M5.5 20a6.5 6.5 0 0 1 13 0" /></svg></a><button type="button" class="menu-button" :aria-expanded="menuOpen" aria-label="Toggle navigation" @click="menuOpen = !menuOpen"><i></i><i></i></button></div></div><form v-if="searchOpen" class="search-panel" @submit.prevent="submitSearch"><label for="header-search" class="sr-only">Search products</label><input id="header-search" v-model="searchTerm" type="search" placeholder="Search gear, brands, and categories" autofocus /><button class="btn btn-primary" type="submit">Search</button></form></header>
</template>
